author: 若离QQ：2909998156
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: false
# 推送方式：0：邮件推送；1：qmsg推送；2：待添加更多推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: 'cece0829998d4516e840591278f993ac'


users:
# 2018XXX
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20182786'
      #name: ''
      #password 密码
      password: 'Jianghaom152'
      #address 地址，定位信息
      address: '北京市朝阳区小红门路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: '1522068546@qq.com'
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 116.454409
      #lat 纬度
      lat: 39.849303
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
#  - user:
#      # 任务类型（收集：0、签到：1、查寝：2）
#      type: 1
#      #username 学号或者工号
#      username: '20182796'
#      #name: '王千一'
#      #password 密码
#      password: 'fan0212.'
#      #address 地址，定位信息
#      address: '中国吉林省长春市大学城路'
#      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
#      sendKey: '2018638110@qq.com'
#      #school 学校全称
#      schoolName: 长春工业大学
#      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#      #lon 经度
#      lon: 125.401194
#      #lat 纬度
#      lat: 44.003081
#      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
#      abnormalReason: ''
#      #photo 签到照片，不需要可不填，或者直接删除
#      photo: sign.jpg
#      # 是否检查表单的标题（1代表检查，0代表不检查）
#      checkTitle: 1
#      # 表单信息
#      forms:
#        - form:
#            title: 早测温
#            value: 37.3度以下
#        - form:
#            title: 午测温
#            value: 37.3度以下
#        - form:
#            title: 晚测温
#            value: 37.3度以下
#        - form:
#            title: 健康状况
#            value: 健康
#
#  - user:
#      # 任务类型（收集：0、签到：1、查寝：2）
#      type: 1
#      #username 学号或者工号
#      username: '20182778'
#      #name: '崔玉涛'
#      #password 密码
#      password: 'cuishuaishuai6'
#      #address 地址，定位信息
#      address: '中国吉林省长春市大学城路'
#      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
#      sendKey: '@qq.com'
#      #school 学校全称
#      schoolName: 长春工业大学
#      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#      #lon 经度
#      lon: 125.401194
#      #lat 纬度
#      lat: 44.003081
#      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
#      abnormalReason: ''
#      #photo 签到照片，不需要可不填，或者直接删除
#      photo: sign.jpg
#      # 是否检查表单的标题（1代表检查，0代表不检查）
#      checkTitle: 1
#      # 表单信息
#      forms:
#        - form:
#            title: 早测温
#            value: 37.3度以下
#        - form:
#            title: 午测温
#            value: 37.3度以下
#        - form:
#            title: 晚测温
#            value: 37.3度以下
#        - form:
#            title: 健康状况
#            value: 健康
#
#
#  - user:
#      # 任务类型（收集：0、签到：1、查寝：2）
#      type: 1
#      #username 学号或者工号
#      username: '20184098'
#      #name: 'hot stuff'
#      #password 密码
#      password: 'wenyahan1'
#      #address 地址，定位信息
#      address: '吉林省长春市宽城区地理路'
#      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
#      sendKey: '@qq.com'
#      #school 学校全称
#      schoolName: 长春工业大学
#      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#      #lon 经度
#      lon: 125.401801
#      #lat 纬度
#      lat: 43.997641
#      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
#      abnormalReason: ''
#      #photo 签到照片，不需要可不填，或者直接删除
#      photo: sign.jpg
#      # 是否检查表单的标题（1代表检查，0代表不检查）
#      checkTitle: 1
#      # 表单信息
#      forms:
#        - form:
#            title: 早测温
#            value: 37.3度以下
#        - form:
#            title: 午测温
#            value: 37.3度以下
#        - form:
#            title: 晚测温
#            value: 37.3度以下
#        - form:
#            title: 健康状况
#            value: 健康